#ΑΣΚΗΣΗ 3.5. ΓΙΑ ΠΡΟΚΑΘΟΡΙΣΜΕΝΟ ΑΡΙΘΜΟ ΥΠΟΨΗΦΙΩΝ ΠΟΥ ΔΙΝΕΤΑΙ ΑΠΟ ΤΟ ΧΡΗΣΤΗ


#Εντολές στις οποίες πιθανόν να προκύψουν σφάλματα, συντακτικά ή λογικά 
try:
    
    #Διάβασμα του αριθμού των ψηφοφόρων (number_of_voters) από το χρήστη
    number_of_candidates = int(input("Δώσε το πλήθος των υποψηφίων: "))
    
    assert number_of_candidates > 0   #προφανώς πρέπει ο αριθμός των υποψηφίων που θα δωθεί από το χρήστη, να είναι θετικός αριθμός
    
    for i in range (number_of_candidates):
        
        #διάβασμα του ονόματος (name) του χρήστη
        name = input(f"Δωσε το όνομα του {i +1}ου υποψηφίου : ")
       
        
        #Διάβασμα της βαθμολογίας (grade) του π΄ρωτου μαθήματος από τον χρήστη 
        grade1 = float(input(f"Δώσε το βαθμό του 1ου μαθήματος: "))
        
        assert 0<=grade1<=100   #η βαθμολογία και των τριών μαθημάτων κυμαίνεται μεταξύ του 0 και του 100
        
        
        #Διάβασμα της βαθμολογίας (grade) του δεύτερου μαθήματος από τον χρήστη 
        grade2 = float(input(f"Δώσε το βαθμό του 2ου μαθήματος: "))
        
        assert 0<=grade2<=100  #η βαθμολογία και των τριών μαθημάτων κυμαίνεται μεταξύ του 0 και του 100
        
        
        #Διάβασμα της βαθμολογίας (grade) του τρίτου μαθήματος από τον χρήστη 
        grade3 = float(input(f"Δώσε το βαθμό του 3ου μαθήματος: "))
        
        assert 0<=grade3<=100  #η βαθμολογία και των τριών μαθημάτων κυμαίνεται μεταξύ του 0 και του 100
        
        
        
        if (grade1 >=50 and grade2 >=50 and grade3 >=50) or ((grade1 + grade2 + grade3) / 3) >75 :  #TRUE αν ο υποψήφιος πέρασε το διαγωνισμό
            
            print(f"Συγχαρητήρια {name}! Πέρασες με επιτυχία το διαγωνισμό!")
        
        else :    #TRUE αν ο υποψήφιος απέτυχε στο διαγωνισμό
            print(f"Δυστυχώς {name} δεν τα κατάφερες! Καλή τύχη την επόμενη φορά!")
            
    
    

    
#Έλεγχος για συντακτικά λάθη 
except ValueError:
    print(f"{name}, δεν έδωσες κάποιον αριθμό. Παρακαλώ ξαναπροσπάθησε!")
 


#Έλεγχος για λογικά λάθη   
except AssertionError :
  print(f"{name}, μη επιτρεπτή είσοδος. Παρακαλώ ξαναπροσπάθησε!")
